@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Bruno Ramos",
    "email": "brunolemos@bb.com.br",
    "password": "12345678"
}

###

POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Bruno Ramos",
    "email": "323232",
    "password": "12345678"
}


###

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "brunolemos@bb.com.br",
    "password": "12345678"
}

###

 # @name AuthenticantionFailed
POST {{baseUrl}}/questions
Content-Type: application/json


###

 # @name AuthenticantionSuccess
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

