@baseUrl = http://localhost:3333
@authToken = {{authentication.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Bruno Ramos",
    "email": "brunolemos1@bb.com.br",
    "password": "12345678"
}

###

POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Bruno Ramos",
    "email": "brunolemos11@bb.com.br",
    "password": "12345678"
}


###

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "brunolemos1@bb.com.br",
    "password": "12345678"
}

###

 # @name AuthenticantionFailed
POST {{baseUrl}}/questions
Content-Type: application/json


###

 # @name Create-Question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova Pergunta",
    "content": "Conteudo",
    "attachments": ["f003f723-51fc-4880-925f-bdb04f093c24"]
}

###

 # @name FetchRecentQuestion
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

 # @name FetchRecentQuestion2
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

 # @name Create-Answer
POST {{baseUrl}}/questions/6f83be82-374c-4b98-b060-fc867621dc73/answer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova Resposta",
    "content": "Conteudo",
    "attachments": []
}

###

 # @name FetchAnswers
GET {{baseUrl}}/questions/6f83be82-374c-4b98-b060-fc867621dc73/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

 # @name Create Attachment
POST {{baseUrl}}/attachments/
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

 # @name Create Attachment
PATCH {{baseUrl}}/notifications/534f9c52-fd16-4247-be61-3e61db2b26cc/read
Content-Type: application/json
Authorization: Bearer {{authToken}}


